[package]
name = "sal-3dlib"
edition.workspace = true
version.workspace = true

[dependencies]
sal-3dlib-core = { path = "../sal-3dlib-core/" }
parry3d-f64.workspace = true
log.workspace = true
sal-core.workspace = true
obj.workspace = true
stl_io.workspace = true
bincode.workspace = true

[dev-dependencies]
debugging.workspace = true
env_logger.workspace = true
log.workspace = true
testing.workspace = true
sal-sync.workspace = true
